### Домашнее задание**

● Создайте случайную матрицу А1 размерностью 5 на 5

● Транспонируйте матрицу A1

● Найдите обратную матрицу для А1

● Создайте диагональную матрицу - поэлементно перемножив единичную
матрицу I и случайную матрицу A2 размерности 4 на 4

● Создайте нулевую матрицу размерности 3 на 3

● Для всех полученных матриц найдите: определитель, ранг и собственные
значения

● Проанализируйте результаты

###### Создайте случайную матрицу А1 размерностью 5 на 5

In [2]:
import numpy as np

In [34]:
A1 = np.random.random((5,5))
A1

array([[0.10536894, 0.26764989, 0.12429827, 0.94134178, 0.70140835],
       [0.97559605, 0.59617329, 0.44936631, 0.93575725, 0.37152166],
       [0.41207945, 0.8855144 , 0.20914217, 0.44362982, 0.80255445],
       [0.33794038, 0.07827669, 0.99039062, 0.3425646 , 0.95131018],
       [0.55086446, 0.9183059 , 0.05119245, 0.47655594, 0.07571383]])

###### Транспонируйте матрицу A1

In [35]:
B1 = A1.transpose()
B1

array([[0.10536894, 0.97559605, 0.41207945, 0.33794038, 0.55086446],
       [0.26764989, 0.59617329, 0.8855144 , 0.07827669, 0.9183059 ],
       [0.12429827, 0.44936631, 0.20914217, 0.99039062, 0.05119245],
       [0.94134178, 0.93575725, 0.44362982, 0.3425646 , 0.47655594],
       [0.70140835, 0.37152166, 0.80255445, 0.95131018, 0.07571383]])

######   Найдите обратную матрицу для А1

In [36]:
A1_inverse = np.linalg.inv(A1)
A1_inverse

array([[-1.37731813,  2.34136877,  1.68303541, -1.1080644 , -2.64709063],
       [ 0.14377283, -1.27457607, -0.36256442,  0.52417331,  2.17946207],
       [ 0.23695027, -1.24710057, -2.06378812,  1.84861917,  2.57308446],
       [ 1.32895086, -0.21979494, -1.35367937,  0.16469516,  1.04665898],
       [-0.24779246,  0.65061558,  2.0679835 , -0.58219147, -2.2946767 ]])

###### Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

In [46]:
x1 = np.eye(4)
A2 = np.random.random((4,4))

In [47]:
x1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
A2

array([[0.4674959 , 0.50427053, 0.30261874, 0.57136213],
       [0.74597692, 0.89696134, 0.8493476 , 0.45159518],
       [0.06041751, 0.99454098, 0.73708035, 0.14514037],
       [0.82387681, 0.38647001, 0.4966595 , 0.34259563]])

In [49]:
A3=x1@A2
A3

array([[0.4674959 , 0.50427053, 0.30261874, 0.57136213],
       [0.74597692, 0.89696134, 0.8493476 , 0.45159518],
       [0.06041751, 0.99454098, 0.73708035, 0.14514037],
       [0.82387681, 0.38647001, 0.4966595 , 0.34259563]])

###### Создайте нулевую матрицу размерности 3 на 3

In [21]:
zero = np.zeros([3,3])
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### Для всех полученных матриц найдите: определитель, ранг и собственные значения

In [40]:
# determinant
np.linalg.det(A1)

0.18582418551162208

In [50]:
np.linalg.det(A2)

0.011669723796156783

In [51]:
np.linalg.det(A3)

0.011669723796156783

In [52]:
np.linalg.det(B1)

0.185824185511622

In [53]:
np.linalg.det(A1_inverse)

5.38143082530803

In [54]:
# rank
np.linalg.matrix_rank(A1)

5

In [55]:
np.linalg.matrix_rank(A2)

4

In [56]:
np.linalg.matrix_rank(A3)

4

In [57]:
np.linalg.matrix_rank(B1)

5

In [58]:
np.linalg.matrix_rank(A1_inverse)

5

In [24]:
# egen betydning
np.linalg.eig(A1)

(array([ 2.45628966+0.j        , -0.58981069+0.j        ,
         0.32968118+0.33228643j,  0.32968118-0.33228643j,
         0.17567537+0.j        ]),
 array([[-0.33527711+0.j        ,  0.74837099+0.j        ,
         -0.25145296-0.07126683j, -0.25145296+0.07126683j,
         -0.46844903+0.j        ],
        [-0.66653741+0.j        , -0.10323067+0.j        ,
          0.37401508-0.14939059j,  0.37401508+0.14939059j,
          0.79311751+0.j        ],
        [-0.37185291+0.j        , -0.13714063+0.j        ,
         -0.28032893+0.38978867j, -0.28032893-0.38978867j,
         -0.05805549+0.j        ],
        [-0.40505903+0.j        , -0.07531689+0.j        ,
          0.65885035+0.j        ,  0.65885035-0.j        ,
         -0.38489375+0.j        ],
        [-0.37545936+0.j        , -0.63624218+0.j        ,
         -0.1854413 -0.26551053j, -0.1854413 +0.26551053j,
         -0.00254691+0.j        ]]))

In [25]:
np.linalg.eigvals(A1)

array([ 2.45628966+0.j        , -0.58981069+0.j        ,
        0.32968118+0.33228643j,  0.32968118-0.33228643j,
        0.17567537+0.j        ])

In [59]:
np.linalg.eigvals(A2)

array([ 2.26943183,  0.56143713, -0.36139243, -0.02534331])

In [60]:
np.linalg.eigvals(A3)

array([ 2.26943183,  0.56143713, -0.36139243, -0.02534331])

In [61]:
np.linalg.eigvals(B1)

array([ 2.59328928+0.j        , -0.49952338+0.j        ,
       -0.22857546+0.j        , -0.2681138 +0.74544637j,
       -0.2681138 -0.74544637j])

In [62]:
np.linalg.eigvals(A1_inverse)

array([-4.37492278+0.j       , -2.00190829+0.j       ,
       -0.42722173+1.1878198j, -0.42722173-1.1878198j,
        0.38561066+0.j       ])

###### Проанализируйте результаты

In [37]:
A1@(np.linalg.inv(A1))

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00,
         5.55111512e-17,  0.00000000e+00],
       [ 4.16333634e-17,  1.00000000e+00,  1.11022302e-16,
         2.77555756e-17,  3.33066907e-16],
       [-5.55111512e-17,  0.00000000e+00,  1.00000000e+00,
         5.55111512e-17,  2.22044605e-16],
       [ 8.32667268e-17,  0.00000000e+00, -4.44089210e-16,
         1.00000000e+00,  0.00000000e+00],
       [-7.97972799e-17, -4.85722573e-17,  4.44089210e-16,
        -1.59594560e-16,  1.00000000e+00]])

In [63]:
A2@(np.linalg.inv(A2))

array([[ 1.00000000e+00, -8.88178420e-16, -8.88178420e-16,
        -8.88178420e-16],
       [-2.08166817e-16,  1.00000000e+00,  1.33226763e-15,
         0.00000000e+00],
       [-1.02695630e-15,  6.66133815e-16,  1.00000000e+00,
        -1.11022302e-15],
       [ 8.32667268e-17,  8.88178420e-16,  8.88178420e-16,
         1.00000000e+00]])

In [38]:
A3@(np.linalg.inv(A3))

array([[ 1.00000000e+00, -2.22044605e-16,  2.22044605e-16,
        -2.08166817e-17],
       [-4.44089210e-16,  1.00000000e+00,  0.00000000e+00,
        -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
         1.00000000e+00]])

In [64]:
B1@(np.linalg.inv(B1))

array([[ 1.00000000e+00, -2.22044605e-16,  4.44089210e-16,
         0.00000000e+00,  2.22044605e-16],
       [ 4.44089210e-16,  1.00000000e+00, -4.44089210e-16,
        -2.22044605e-16,  4.44089210e-16],
       [-8.32667268e-17,  8.32667268e-17,  1.00000000e+00,
        -6.93889390e-18, -2.08166817e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00],
       [ 6.38378239e-16,  2.77555756e-17, -3.60822483e-16,
        -3.88578059e-16,  1.00000000e+00]])

In [43]:
a_1 = np.linalg.det(A1)
a_1

0.18582418551162208

In [44]:
a_2 = np.linalg.det(np.linalg.inv(A1))
a_2

5.38143082530803

In [45]:
1/a_1

5.381430825308025